### ISSUE TITLE
About Edmot

### ISSUE THREAD

**Issue by Liuxx21** [benedekrozemberczki/EdMot#1]
Hello,
thanks for the awesome work!!

I have two questions about this code.

The first one is :

in the code below,
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
    def _fill_blocks(self):
        """
        Filling the dense blocks of the adjacency matrix.
        """
        new_edges = [(n_1, n_2) for nodes in self.blocks for n_1 in nodes for n_2 in nodes if n_1!= n_2]
        new_graph = nx.from_edgelist(new_edges)
        self.graph = nx.disjoint_union(self.graph, new_graph)
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
when using the nx.disjoint_union() function to enhance the graph，this function will lead the total count of node in graph rise from 2708 to 2946. I wonder if this will cause some problem.

The second one is :

The proposed model in the original paper(Edmot by Pei-Zhen Li) noticed that there are 4 steps. But I found that your code only derive a clique from the largest connected component without partitioning the component into modules, which is different from the paper.

![image](https://user-images.githubusercontent.com/22791437/75034292-dff86d00-54e7-11ea-8b99-406f2158ed5c.png)

wait for your reply:)

Hope it helps :)

**Comment by benedekrozemberczki** [comment]
1.  Was resolved.
2. If you take a closer look You will see that the number of components is a parameter.

**Comment by ZzyChris97** [comment]
good project!

**Comment by Rico-Lee** [comment]
I think his 2nd question discussed here is talk about the pre-partition procedure in this algorithm.

It's mentioned in the **abstract**:

> Firstly, a motif-based hypergraph is constructed and the **top K largest connected components in the hypergraph are partitioned into modules.** Afterwards, **the connectivity structure within each module is strengthened by constructing an edge set to derive a clique from each module.** Based on the new edge set, the original connectivity structure of the input network is enhanced to generate a rewired network, whereby the motif-based higher-order structure is leveraged and the hypergraph fragmentation issue is well addressed...

And this is also reflected in the **pseudo code**:
![image](https://user-images.githubusercontent.com/61367536/75102198-9b252100-5622-11ea-846b-e8012f9ebeda.png)

As step 3 said, we should apply a partition algorithm S(may be Louvain or others) to partition each connected component 𝜑𝑙 ∈ Φ𝐾 into modules.

I think this is not to be omitted to EdMot, because the goal of this step is to detect the high order community structure, hence we can leverge both high-order and low-order connectivity pattern by enhance the graph by high order cliques(derive from modules, not directly from the components).

The [matlab version code](https://github.com/lipzh5/EdMot_pro ) also follow this step.

And I reasonably think we should add a function(maybe called extract_modules??) after extract components. So the blocks to be filled is these modules in fact.
`    def fit(self):
        """
        Clustering the target graph.
        """
        self._calculate_motifs()
        self._extract_components()
        self._extract_modules()
        self._fill_blocks()
        partition = community.best_partition(self.graph)
        return partition`

Your project is perfect, I love your code stylish because it's efficient and beautiful.

So I just give a little advice on my understanding of the paper

Hope it helps :）
